// list of mutations
export const TEST_MUTATION = 'TEST_MUTATION'
export const SET_ERROR = 'SET_ERROR'
export const RESET_AUTH = 'RESET_AUTH'
// printer mutations
export const GET_PRINTER = 'GET_PRINTER'
export const GET_PRINTERS = 'GET_PRINTERS'
export const GO_BACK_TO_PRINTERS_LIST = 'GO_BACK_TO_PRINTERS_LIST'
export const RESET_ACTIVE_PRINTER = 'RESET_ACTIVE_PRINTER'
export const UPDATE_PRINTER_STORE = 'UPDATE_PRINTER_STORE'
export const PRINTER_CREATED = 'PRINTER_CREATED'
export const PRINTER_UPDATED = 'PRINTER_UPDATED'
// scanner mutations
export const GET_SCANNER = 'GET_SCANNER'
export const GET_SCANNERS = 'GET_SCANNERS'
export const GO_BACK_TO_SCANNERS_LIST = 'GO_BACK_TO_SCANNERS_LIST'
export const RESET_ACTIVE_SCANNER = 'RESET_ACTIVE_SCANNER'
export const UPDATE_SCANNER_STORE = 'UPDATE_SCANNER_STORE'
export const SCANNER_CREATED = 'SCANNER_CREATED'
export const SCANNER_UPDATED = 'SCANNER_UPDATED'

export const CLEAR_ERROR = 'CLEAR_ERROR'
