// list of mutations
export const TEST_MUTATION = 'TEST_MUTATION'
export const SET_ERROR = 'SET_ERROR'
export const CLEAR_ERROR = 'CLEAR_ERROR'
export const ASSIGN_CREDS = 'ASSIGN_CREDS'
export const RANDOM_STATE = 'RANDOM_STATE'
export const LOADING = 'LOADING'
export const LOADING_PROPERTY = 'LOADING_PROPERTY'
export const SET_CODE = 'SET_CODE'
export const SET_TOKEN = 'SET_TOKEN'
export const SET_PROPERTY_META_DATA = 'SET_PROPERTY_META_DATA'
export const SET_PROPERTY = 'SET_PROPERTY'
